paths:
  urbanSound8K: "/home/g0d/Downloads/urbanSound8K"

preprocessing:
  numOfMFCCoeffs: 40
  hopLength: 512
  melSpectrogramsFolder: melSpectrograms
  audioExtensions: 
    - ".wav" 
    - ".mp3"
    - ".aac"
    - ".flac"
    - ".ogg"
    - ".m4a"
    - ".wma" 
    - ".aiff"
    - ".opus"
    - ".amr"
    - ".mid"
    - ".midi"
    - ".mp2"